config/routes.rb
Rails.application.routes.draw do
  root 'citations#index'

  resources :citations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/citation.rb
# frozen_string_literal: true

class Citation < ApplicationRecord
  validates :text, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/citations_controller.rb
# frozen_string_literal: true

class CitationsController < ApplicationController
  def index
    @citations = Citation.all.order(created_at: :desc).paginate(
      page: params[:page], per_page: 12
    )
  end

  def new
    @citation = Citation.new
  end

  def create
    @citation = Citation.new(citation_params)

    if @citation.save
      redirect_to '/'
    else
      render :new
    end
  end

  private

  def citation_params
    params.require(:citation).permit(:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/citations_helper.rb
module CitationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/citations/index.html.erb
<h1>List of all quotes</h1>
</p><%= link_to 'Add new quote', new_citation_path %></p>
<p>
  <table style="width: 60%">
    <tr>
      <th style="width: 15%">Added at</th>
      <th>Quotes</th>
    </tr>
    <% @citations.each do |citation| %>
      <tr></p>
        <td><%= citation.created_at.strftime('%d %B %Y') %></td>
        <td><%= citation.text %></td>
      </tr>
    <% end %>
  </table>
  <p><%= will_paginate @citations %></p>

app/views/citations/new.html.erb
<h1>New quotes</h1>
<%= link_to 'Back', citations_path %>

<% if @citation.errors.any? %>
  <div>
    <h2><%= pluralize(@citation.errors.count, 'error') %>
      prohibited this article begin from saved:</h2>
    <ul>
      <% @citation.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for :citation, url: citations_path do |f| %>
<p>
  <%= f.label :Quote %><br>
  <%= f.text_area :text %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NetguruPage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>